/**
 * pi hooks bridge for the "memory-vault" Claude Code plugin — generated by tools/pi-package.py.
 *
 * Replays the plugin's hooks/hooks.json inside pi, running the same scripts with the
 * same stdin JSON Claude Code sends, so one hook implementation serves both harnesses.
 *
 *   PreToolUse  Bash / Edit|Write   -> tool_call   (exit 2 blocks the call, stderr is the reason)
 *   PostToolUse Bash / Edit|Write   -> tool_result (exit 2 -> stderr is steered to the model)
 *   Stop / SubagentStop             -> agent_end   (exit 2 -> stderr is sent as a follow-up, once)
 *   SessionStart                    -> before_agent_start (stdout appended to the system prompt, once)
 *
 * Active only where Claude Code enables the plugin: `.claude/settings.json`
 * enabledPlugins["memory-vault@…"] — project file (cwd up to git root) wins over
 * ~/.claude/settings.json. Set PI_CLAUDE_HOOKS=0 to disable every bridge.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const PLUGIN = "memory-vault";
const ROOT = resolve(dirname(new URL(import.meta.url).pathname), "../..");
const TOOL_NAMES: Record<string, string> = { bash: "Bash", edit: "Edit", write: "Write", read: "Read" };

type Hook = { command: string; timeout?: number };
type Entry = { matcher?: string; hooks: Hook[] };
type HooksFile = { hooks?: Record<string, Entry[]> };

function loadHooks(): Record<string, Entry[]> {
	try {
		return (JSON.parse(readFileSync(join(ROOT, "hooks", "hooks.json"), "utf8")) as HooksFile).hooks ?? {};
	} catch {
		return {};
	}
}

function enabledFlag(file: string): boolean | undefined {
	if (!existsSync(file)) return undefined;
	try {
		const ep = JSON.parse(readFileSync(file, "utf8")).enabledPlugins ?? {};
		const key = Object.keys(ep).find((k) => k.startsWith(`${PLUGIN}@`));
		return key === undefined ? undefined : ep[key] === true;
	} catch {
		return undefined;
	}
}

function enabledIn(cwd: string): boolean {
	if (process.env.PI_CLAUDE_HOOKS === "0") return false;
	let dir = resolve(cwd);
	for (;;) {
		const flag = enabledFlag(join(dir, ".claude", "settings.json"));
		if (flag !== undefined) return flag;
		if (existsSync(join(dir, ".git"))) break;
		const parent = dirname(dir);
		if (parent === dir) break;
		dir = parent;
	}
	return enabledFlag(join(homedir(), ".claude", "settings.json")) === true;
}

function matches(entry: Entry, toolName: string): boolean {
	if (!entry.matcher || entry.matcher === "*") return true;
	return new RegExp(`^(${entry.matcher})$`).test(toolName);
}

function run(hook: Hook, payload: Record<string, unknown>, cwd: string) {
	const cmd = hook.command.replaceAll("${CLAUDE_PLUGIN_ROOT}", ROOT);
	const r = spawnSync("bash", ["-c", cmd], {
		cwd,
		input: JSON.stringify(payload),
		encoding: "utf8",
		timeout: (hook.timeout ?? 60) * 1000,
		env: { ...process.env, CLAUDE_PLUGIN_ROOT: ROOT, CLAUDE_PROJECT_DIR: cwd },
	});
	return { code: r.status, out: (r.stdout || "").trim(), err: (r.stderr || "").trim() };
}

function toolInput(toolName: string, input: Record<string, unknown>): Record<string, unknown> | null {
	if (toolName === "bash" && typeof input.command === "string") return { command: input.command };
	if ((toolName === "edit" || toolName === "write") && typeof input.path === "string") {
		return { file_path: input.path, content: input.content, old_string: input.oldText, new_string: input.newText };
	}
	return null;
}

export default function (pi: ExtensionAPI) {
	const hooks = loadHooks();
	const pre = hooks.PreToolUse ?? [];
	const post = hooks.PostToolUse ?? [];
	const stop = [...(hooks.Stop ?? []), ...(hooks.SubagentStop ?? [])];
	let stopActive = false;
	let sessionStarted = false;

	pi.on("input", () => {
		stopActive = false;
	});

	pi.on("before_agent_start", async (event, ctx) => {
		if (!enabledIn(ctx.cwd)) return;
		// SessionStart hooks: stdout is context (Claude Code appends it to the
		// conversation); here it rides along in the system prompt, once per run.
		const injected: string[] = [];
		if (!sessionStarted) {
			sessionStarted = true;
			for (const entry of hooks.SessionStart ?? []) {
				for (const hook of entry.hooks) {
					const r = run(hook, { hook_event_name: "SessionStart", source: "startup", session_id: "", transcript_path: "", cwd: ctx.cwd }, ctx.cwd);
					if (r.code === 0 && r.out) injected.push(r.out);
				}
			}
		}
		const extra = injected.length ? `\n\n<session-start name="${PLUGIN}">\n${injected.join("\n\n")}\n</session-start>` : "";
		return {
			systemPrompt: `${event.systemPrompt}\n\n<plugin-root name="${PLUGIN}">\${CLAUDE_PLUGIN_ROOT} in ${PLUGIN} skills, prompts and agents means ${ROOT}</plugin-root>${extra}`,
		};
	});

	if (pre.length) {
		pi.on("tool_call", async (event, ctx) => {
			if (!enabledIn(ctx.cwd)) return;
			const claudeName = TOOL_NAMES[event.toolName];
			const ti = claudeName && toolInput(event.toolName, event.input as Record<string, unknown>);
			if (!ti) return;
			for (const entry of pre) {
				if (!matches(entry, claudeName)) continue;
				for (const hook of entry.hooks) {
					const r = run(hook, { hook_event_name: "PreToolUse", tool_name: claudeName, tool_input: ti, cwd: ctx.cwd }, ctx.cwd);
					if (r.code === 2) return { block: true, reason: r.err || r.out || `blocked by ${PLUGIN} hook` };
				}
			}
		});
	}

	if (post.length) {
		pi.on("tool_result", async (event, ctx) => {
			if (!enabledIn(ctx.cwd)) return;
			const claudeName = TOOL_NAMES[event.toolName];
			const ti = claudeName && toolInput(event.toolName, event.input as Record<string, unknown>);
			if (!ti) return;
			const feedback: string[] = [];
			for (const entry of post) {
				if (!matches(entry, claudeName)) continue;
				for (const hook of entry.hooks) {
					const r = run(
						hook,
						{ hook_event_name: "PostToolUse", tool_name: claudeName, tool_input: ti, tool_response: { content: event.content }, cwd: ctx.cwd },
						ctx.cwd,
					);
					if (r.code === 2 && (r.err || r.out)) feedback.push(r.err || r.out);
				}
			}
			if (feedback.length) {
				pi.sendMessage({ customType: `${PLUGIN}-hook`, content: feedback.join("\n\n"), display: true }, { deliverAs: "steer" });
			}
		});
	}

	if (stop.length) {
		pi.on("agent_end", async (_event, ctx) => {
			if (!enabledIn(ctx.cwd)) return;
			const failures: string[] = [];
			for (const entry of stop) {
				for (const hook of entry.hooks) {
					const r = run(hook, { hook_event_name: "Stop", session_id: "", transcript_path: "", stop_hook_active: stopActive, cwd: ctx.cwd }, ctx.cwd);
					if (r.code === 2 && (r.err || r.out)) failures.push(r.err || r.out);
				}
			}
			if (failures.length && !stopActive) {
				stopActive = true;
				pi.sendMessage(
					{ customType: `${PLUGIN}-gate`, content: failures.join("\n\n"), display: true },
					{ deliverAs: "followUp", triggerTurn: true },
				);
			}
		});
	}
}
